format the repo and add csv support in create options
postmen/postmen-sdk-js pull request #2
Opened 2016-12-12 08:34 UTC by hans-lizihan

@adamliuxy @suddi 

1. update style
2. update an option in the create method to support create label from csv.

2016-12-13 03:14 UTC, suddi requested changes

2016-12-13 03:14 UTC, suddi commented on README.md
> -| Argument                       | Required                               | Type    | Default   | Description                                       |
Why remove all of this?

2016-12-13 03:14 UTC, suddi commented on lib/payload.js
> +		if (config.csv) {
Can we keep this generic, rather than configuring specifically for `csv`?

2016-12-13 03:14 UTC, suddi commented on lib/payload.js
> +		if (config.csv) {
We just pass additional headers, and handle it in the code.

2016-12-13 04:03 UTC, hans-lizihan commented on README.md
> -| Argument                       | Required                               | Type    | Default   | Description                                       |
whoops

2016-12-13 04:04 UTC, hans-lizihan commented on lib/payload.js
> +		if (config.csv) {
no, it seems that the SDK doesn't provide such functionality to customize the headers.

I could do so, but doing so may involves more changes to this SDK.

2016-12-13 08:20 UTC, hans-lizihan commented on README.md
> -| Argument                       | Required                               | Type    | Default   | Description                                       |
fixed.

2016-12-15 02:45 UTC, suddi approved these changes

2016-12-15 02:45 UTC, merged